### ISSUE TITLE
deps.edn

### ISSUE THREAD

**Issue by bitfilms** [phronmophobic/membrane#1]
Hello - trying to get started using membrane with clojure 1.10.1 on a mac (running clj from command line).

I added the git url with sha for membrane to my deps.edn file, but when I run clj I get:

> Error building classpath. Manifest type not detected when finding deps for com.phronmophobic/membrane in coordinate {:git/url "https://github.com/phronmophobic/membrane.git", :tag "0.9.8-beta", :sha "c5a15340041c71a8208f865b0be9c85ef62c2883"}

[This page](https://ask.clojure.org/index.php/8507/failure-on-github-import-via-deps) suggests that adding a deps.edn to the repo would help figure out the dependencies. For now I will try to just extract them from project.clj and put them in my local deps.edn but I thought I'd log this as a request so that others might benefit as well.

Thanks!

**Comment by phronmophobic** [comment]
Seems like a straightforward improvement! Will work on that today.

**Comment by phronmophobic** [comment]
I was able to get membrane to work using deps.edn with the following deps.edn:

```
{:deps
 {com.phronemophobic/membrane {:mvn/version "0.9.8-beta"}}}
```

Still looking into what it would take to support deps.edn for git commits, but hopefully the above is enough to get you up and running!

**Comment by phronmophobic** [comment]
I've also updated the README.md with the deps.edn dependency based off your feedback: https://github.com/phronmophobic/membrane/commit/f051866ec7e5606a436517b86bb042e498c79deb

**Comment by bitfilms** [comment]
Outstanding! Thank you! It worked perfectly. Nice clean solution and much appreciated.
